In [17]:
#Task1: Creating NumPy Arrays
#1.import numpy as ip
import numpy as np

#2. 1D of integer from 1 to 10
oneDim = np.arange(1,11)
print(oneDim)
print(f"Shape:{oneDim.shape}")
print(f"Data type: {oneDim.dtype}")
# 2D of shape (3,3) with value 1 to 9

twoDim = np.arange(1,10).reshape(3,3)
print(twoDim)
print(f"Shape:{twoDim.shape}")
print(f"Data type:{twoDim.dtype}")

# Numpy array from the list
array = np.array([10,20,30,40,50])
print(array)
print(f"Shape:{array.shape}")
print(f"Data type:{array.dtype}")

[ 1  2  3  4  5  6  7  8  9 10]
Shape:(10,)
Data type: int64
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape:(3, 3)
Data type:int64
[10 20 30 40 50]
Shape:(5,)
Data type:int64


In [23]:
#Task 2: Important Mathematical Operations
A = np.array([10,20,30,40])
B = np.array([1,2,3,4])
print(A+B)
print(A - B)
print(A*B)
print(A/B)
print(A**2)

[11 22 33 44]
[ 9 18 27 36]
[ 10  40  90 160]
[10. 10. 10. 10.]
[ 100  400  900 1600]


In [ ]:
#Task 3: Importand NumPy Mathematical Formula
values = np.array([2,4,6,8,10])
print(np.sqrt(values))
print(np.exp(values))
print(np.log(values))
print(np.sum(values))
print(np.cumsum(values))

[1.41421356 2.         2.44948974 2.82842712 3.16227766]
[7.38905610e+00 5.45981500e+01 4.03428793e+02 2.98095799e+03
 2.20264658e+04]
[0.30103    0.60205999 0.77815125 0.90308999 1.        ]
30
[ 2  6 12 20 30]


In [36]:
#Task 4: Aggregation Operation
data = np.array([[10,20,30],
                 [40,50,60],
                 [70,80,90]])
print(np.sum(data, axis = 0))
print(np.sum(data, axis = 1))
print(np.min(data))
print(np.max(data))
print(np.mean(data))

[120 150 180]
[ 60 150 240]
10
90
50.0


In [ ]:
#Task 5: Statistical Operation (Core Focus)
marks = np.array([78, 85,90,66,72,88,95,60])
print(np.mean(marks))
print(np.median(marks))
print(np.var(marks))
print(np.std(marks))
print(np.min(marks))
print(np.max(marks))
print(np.ptp(marks))

79.25
81.5
134.1875
11.583932838203095
10
95
35


In [68]:
#Task 6: Percentiles and sorting
sort = np.sort(marks)
print(sort)
print(np.percentile(marks,25))
print(np.percentile(marks,50))
print(np.percentile(marks,75))
print(sort[ sort > np.average(marks)].size)

[60 66 72 78 85 88 90 95]
70.5
81.5
88.5
4


In [69]:
#Task 7: Mini Use Case: Sales Analysis
sales = np.array([1200,1500,900,2000,1800,1700,1600])
print(f"Total weekly sales: {np.sum(sales)}")
print(f"Average Daily Sales: {np.average(sales)}")
print(f"Highest sale:{np.max(sales)} Lowest sales: {np.min(sales)}")
print(f"Standard deviation of sales: {np.std(sales)}")
print(np.argwhere(sales > np.average(sales)))

Total weekly sales: 10700
Average Daily Sales: 1528.5714285714287
Highest sale:2000 Lowest sales: 900
Standard deviation of sales: 345.2298849598449
[[3]
 [4]
 [5]
 [6]]
