In [2]:
import numpy as np

In [4]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [5]:
np.array([[1,2,3],[3,4,5]])

array([[1, 2, 3],
       [3, 4, 5]])

In [7]:
np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[10,11]]])

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [10, 11]]])

In [6]:
np.arange(5)
np.arange(4,14)
np.arange(1,30,3)

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28])

In [13]:
np.linspace(2,3,10)

array([2.        , 2.11111111, 2.22222222, 2.33333333, 2.44444444,
       2.55555556, 2.66666667, 2.77777778, 2.88888889, 3.        ])

In [15]:
np.random.rand(3,3)

array([[0.68985141, 0.74770042, 0.32303869],
       [0.49794111, 0.69294854, 0.41493263],
       [0.40173937, 0.33212958, 0.629435  ]])

In [37]:
a= np.random.randint(1,10,(2,4))
print(a)
print(a.shape)
print(a.ndim)
print(a.size)
print(a.dtype)
print(a.itemsize)

[[3 7 1 2]
 [1 5 5 6]]
(2, 4)
2
8
int32
4


In [ ]:
#Reshape
a = np.arange(12)
print(a[[0, 2, 5]])
print(a.reshape(3,4))
print(a.reshape(2,2,3))
print(a.reshape(-1,3))


[0 2 5]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[0 2 5]


In [44]:
a = np.array([1,2,3,4,5,6,7])
print(a[[0,2,3]])

[1 3 4]
